[package]
name = "rustnao"
version = "0.1.0"
authors = ["Clement Tsang <clementjhtsang@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/ClementTsang/RustNAO"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.9.17"
serde_json = "1.0"
url = "1.7.2"